filter:
    excluded_paths:
        - 'vendor/*'
        - 'DEV/*'
    paths: {  }
before_commands:
    - git clone https://github.com/wimg/PHPCompatibility
    - git clone https://github.com/Pheromone/phpcs-security-audit
tools:
    js_hint: true
    php_analyzer:
        config:
            verify_php_doc_comments:
                enabled:              true
                parameters:           true
                return:               true
                suggest_more_specific_types:  true
                ask_for_return_if_not_inferrable:  true
                ask_for_param_type_annotation:  true
    php_code_sniffer: 
        enabled: false
        config:
            ruleset: ../PHPCompatibility/ruleset.xml
            ruleset: ../Pheromone/example_base_ruleset.xml
    php_cpd:
        enabled: true
        command: phpcpd
        excluded_dirs: {  }
        names:
            - '*.php'
        min_lines: 5
        min_tokens: 70
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'app/*'
                - 'web/*'
            paths: {  }
    php_loc: false
    php_mess_detector: false
    php_pdepend:
        excluded_dirs:
            - vendor
        enabled: false
        command: pdepend
        configuration_file: null
        suffixes:
            - php
before_commands: {  }
after_commands: {  }
artifacts: {  }