filter:
    excluded_paths:
        - 'vendor/*'
		- 'DEV/*'
    paths: {  }
tools:
    js_hint: true
    php_analyzer: false
    php_code_sniffer: false
    php_cpd:
        enabled: true
        command: phpcpd
        excluded_dirs: {  }
        names:
            - '*.php'
        min_lines: 5
        min_tokens: 70
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'app/*'
                - 'web/*'
            paths: {  }
    php_loc: false
    php_mess_detector: false
    php_pdepend:
        excluded_dirs:
            - vendor
        enabled: false
        command: pdepend
        configuration_file: null
        suffixes:
            - php
before_commands: {  }
after_commands: {  }
artifacts: {  }